#!/usr/bin/env python3
"""Generate the 12 axolotl YAML configs for the closed-task FT sweep.

Writes ft_configs/ft_<student>_<cond>.yml for student in {ministral_3b, gemma_E4B, qwen35_4b}
and cond in {DAUTH, DA, DB, DC}.

Cloned from axolotl_dev/configs/dgt_en-fr_qlora-training-mistral-small-instruct-1node.yml
and adjusted for ~12k-row classification FT (vs 200k-row translation):
  - lora_r: 64 (down from 256)
  - sequence_len: 1024
  - train_on_inputs: false (instruction tuning standard, differs from translation)
  - num_epochs: 5, early_stopping_patience: 3
  - lr 2e-5 cosine, warmup_steps 100
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ft_configs"
OUT.mkdir(parents=True, exist_ok=True)

STUDENTS = {
    "ministral_3b": {
        "base_model": "mistralai/Ministral-3-3B-Instruct-2512",
        "chat_template": "tokenizer_default",
    },
    "gemma_E4B": {
        "base_model": "google/gemma-4-E4B-it",
        "chat_template": "tokenizer_default_fallback_llama3",   # safer than gemma's native template under axolotl
    },
    "qwen35_4b": {
        "base_model": "Qwen/Qwen3.5-4B",
        "chat_template": "tokenizer_default",
    },
}

CONDS = ["DAUTH", "DA"]

TEMPLATE = """# Auto-generated by scripts/gen_ft_configs.py - do not edit by hand.
# Closed-task QLoRA FT for gender-referent classification.
# Student: {base_model}
# Condition: {cond} ({cond_desc})

base_model: {base_model}
chat_template: {chat_template}

datasets:
  - path: {root}/ft_data/closed_{cond}_train.jsonl
    type: chat_template
    system: ""

test_datasets:
  - path: {root}/ft_data/closed_{cond}_val.jsonl
    type: chat_template
    split: train
    system: ""

dataset_prepared_path: {root}/ft_outputs/ft_{student}_{cond}/prepared

output_dir: {root}/ft_outputs/ft_{student}_{cond}

# QLoRA configuration
adapter: qlora
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

# Sequence and packing
sequence_len: {seq_len}
sample_packing: false                  # DDP+LoRA stride bug under packed batches; cheap on 12k rows
eval_sample_packing: false

# 4-bit quantisation
load_in_4bit: true
bnb_config_kwargs:
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: bfloat16

# Training
train_on_inputs: false                   # only learn the assistant turn
gradient_accumulation_steps: {grad_accum}
micro_batch_size: {micro_batch}
eval_batch_size: 4
num_epochs: 5

dataloader_num_workers: 4
dataloader_pin_memory: true
dataloader_prefetch_factor: 2

# Optimiser
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2.0e-5
weight_decay: 0.01
max_grad_norm: 0.5
cosine_min_lr_ratio: 0.05
warmup_steps: 100

# Mixed precision
bf16: true
tf32: false

# Memory optimisation
gradient_checkpointing: false          # DDP+LoRA reentrant-backward incompat; 4B QLoRA fits on 80GB without it
flash_attention: true

# DDP fix for non-uniform parameter usage across LoRA modules (some Qwen3.5 branches not always active)
ddp_find_unused_parameters: true

# Eval / save / early stopping
eval_strategy: steps
eval_steps: 100
save_strategy: steps
save_steps: 100
logging_steps: 10
early_stopping_patience: 3
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
save_total_limit: 2

# Loss
label_smoothing_factor: 0.001

# Loss watchdog (catastrophic-spike detection)
loss_watchdog_threshold: 5.0
loss_watchdog_patience: 5

# wandb (optional; left blank by default)
wandb_project:
wandb_entity:
wandb_watch:
wandb_name: ft_{student}_{cond}
wandb_log_model:
"""

COND_DESC = {
    "DAUTH": "authentic ambiguous-only - no synthetic masc/fem variants",
    "DA":    "labels-only on full 2/2/2 contrastive synthetic data",
}


def _hyperparams(cond: str) -> dict:
    return {"seq_len": 1024, "micro_batch": 8, "grad_accum": 2}


def main() -> None:
    written = 0
    for student, info in STUDENTS.items():
        for cond in CONDS:
            hp = _hyperparams(cond)
            yaml = TEMPLATE.format(
                root=str(ROOT),
                base_model=info["base_model"],
                chat_template=info["chat_template"],
                student=student,
                cond=cond,
                cond_desc=COND_DESC[cond],
                **hp,
            )
            path = OUT / f"ft_{student}_{cond}.yml"
            path.write_text(yaml)
            print(f"  wrote {path.relative_to(ROOT)}")
            written += 1
    print(f"\n  Generated {written} YAML configs in {OUT.relative_to(ROOT)}/.")


if __name__ == "__main__":
    main()
